# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  angularFolder: './SpaceBook-Angular'



steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'teamatmc'
    scannerMode: 'MSBuild'
    projectKey: 'TeamATMC_P2_ATMC'
    projectName: 'P2_ATMC'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet build ./SpaceBook-Backend/SpaceBook.sln --configuration $(buildConfiguration)
  displayName: 'building backend'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: --configuration $(buildConfiguration) --collect "Code Coverage"

- task: PublishCodeCoverageResults@1
  displayName: publish code coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coburtura/coverage.xml'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish and zip'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Trevor Subscription(d4f01992-52b9-4047-8f7d-34d2e08c6987)'
    appType: 'webApp'
    WebAppName: 'ATMCSpaceBook'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

# front-end

# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - task: Npm@1
#   displayName: 'NPM Install'
#   inputs:
#     command: 'install'
#     workingDir: '$(angularFolder)/'

# - task: Npm@1
#   displayName: 'NPM Install Angular CLI'
#   inputs:
#     command: 'custom'
#     workingDir: '$(angularFolder)/'
#     customCommand: 'install -g @angular/cli@latest'

# - task: Npm@1
#   inputs:
#     command: 'custom'
#     workingDir: '$(angularFolder)/'
#     customCommand: 'run ng build --prod'

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(angularFolder)/dist/SpaceBook-Angular/'
#     includeRootFolder: true
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
#     replaceExistingArchive: true

# - task: AzureAppServiceManage@0
#   inputs:
#     azureSubscription: 'Trevor Subscription(d4f01992-52b9-4047-8f7d-34d2e08c6987)'
#     Action: 'Stop Azure App Service'
#     WebAppName: 'ATMCSpaceBook'

# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'Trevor Subscription(d4f01992-52b9-4047-8f7d-34d2e08c6987)'
#     appType: 'webApp'
#     WebAppName: 'ATMCSpaceBook'
#     ResourceGroupName: 'ATMC'
#     packageForLinux: '$(Build.ArtifactStagingDirectory)/frontend.zip'

# - task: AzureAppServiceManage@0
#   inputs:
#     azureSubscription: 'Trevor Subscription(d4f01992-52b9-4047-8f7d-34d2e08c6987)'
#     Action: 'Start Azure App Service'
#     WebAppName: 'ATMCSpaceBook'



