# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'



steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'teamatmc'
    scannerMode: 'MSBuild'
    projectKey: 'TeamATMC_P2_ATMC'
    projectName: 'P2_ATMC'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet build ./SpaceBook-Backend/SpaceBook.sln --configuration $(buildConfiguration)
  displayName: 'building backend'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: --configuration $(buildConfiguration) --collect "Code Coverage"

- task: Npm@1
  displayName: 'Restore Angular Dependencies'
  inputs:
    workingDir: './SpaceBook-Angular/'
    verbose: false

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    workingDir: './SpaceBook-Angular/'
    verbose: false
    customCommand: 'run build'

- task: PublishCodeCoverageResults@1
  displayName: publish code coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coburtura/coverage.xml'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish and zip'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(e220cb1a-5091-46b8-9758-b2b00183ab7f)'
    appType: 'webApp'
    WebAppName: 'ATMC-SpaceBook'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

