# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  angularFolder: './SpaceBook-Angular/'



steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'teamatmc'
    scannerMode: 'MSBuild'
    projectKey: 'TeamATMC_P2_ATMC'
    projectName: 'P2_ATMC'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet build ./SpaceBook-Backend/SpaceBook.sln --configuration $(buildConfiguration)
  displayName: 'building backend'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: --configuration $(buildConfiguration) --collect "Code Coverage"

- task: PublishCodeCoverageResults@1
  displayName: publish code coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coburtura/coverage.xml'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish and zip'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true

- task: Npm@1
  displayName: 'Restore Angular Dependencies'
  inputs:
    workingDir: angularFolder
    verbose: true

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    workingDir: angularFolder
    verbose: true
    customCommand: 'run build'

- task: Npm@1
  displayName: 'Publish Angular'
  inputs:
    command: 'publish'
    workingDir: 'angularFolder'
    verbose: true
    publishRegistry: 'useFeed'
    publishFeed: '0afcca8a-a29e-463f-b238-27cf1b8b59db'


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'SpaceBook Resource Group'
    appType: 'webApp'
    WebAppName: 'ATMCSpaceBook'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/SpaceBook.zip'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Trevor Subscription(d4f01992-52b9-4047-8f7d-34d2e08c6987)'
    appType: 'webApp'
    WebAppName: 'ATMCSpaceBook'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/space-book-angular.zip'

