# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  angularFolder: './SpaceBook-Angular'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'NPM Install'
  inputs:
    command: 'install'
    workingDir: '$(angularFolder)/'

- task: Npm@1
  displayName: 'Restore Angular Dependencies'
  inputs:
    workingDir: $(angularFolder)/
    verbose: true

- task: Npm@1
  displayName: 'NPM Install Angular CLI'
  inputs:
    command: 'custom'
    workingDir: '$(angularFolder)/'
    customCommand: 'install -g @angular/cli@latest'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(angularFolder)/'
    customCommand: 'run ng build --prod --cross-origin anonymous'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(angularFolder)/dist/SpaceBook-Angular/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Trevor Subscription(d4f01992-52b9-4047-8f7d-34d2e08c6987)'
    Action: 'Stop Azure App Service'
    WebAppName: 'space-book'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Trevor Subscription(d4f01992-52b9-4047-8f7d-34d2e08c6987)'
    appType: 'webApp'
    WebAppName: 'space-book'
    deployToSlotOrASE: true
    ResourceGroupName: 'ATMC'
    SlotName: 'production'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Trevor Subscription(d4f01992-52b9-4047-8f7d-34d2e08c6987)'
    Action: 'Start Azure App Service'
    WebAppName: 'space-book'